repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
        name: Terraform fmt
        description: Rewrites all Terraform configuration files to a canonical format

      - id: terraform_validate
        name: Terraform validate
        description: Validates all Terraform configuration files

      - id: terraform_docs
        name: Terraform docs
        description: Inserts input and output documentation into README.md

      - id: terraform_tflint
        name: Terraform TFLint
        description: Validates all Terraform configuration files with TFLint

      - id: terraform_tfsec
        name: Terraform tfsec
        description: Static analysis security scanner for Terraform code
        args:
          - --args=--minimum-severity=MEDIUM

