# ── Cloud SQL ─────────────────────────────────────────────────

resource "google_sql_database_instance" "main" {
  name             = "${var.project_name}-db"
  database_version = "POSTGRES_14"
  region           = var.region

  deletion_protection = true

  settings {
    tier              = "db-custom-2-4096"
    availability_type = "REGIONAL"

    ip_configuration {
      ipv4_enabled    = false
      private_network = var.network_id
      require_ssl     = true
    }

    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      start_time                     = "03:00"
    }
  }
}

resource "google_sql_database" "app" {
  name     = "docuvault"
  instance = google_sql_database_instance.main.name
}

resource "google_sql_user" "app" {
  name     = "docuvault-app"
  instance = google_sql_database_instance.main.name
  password = random_password.db_password.result
}

resource "google_sql_user" "app_iam" {
  name     = var.api_backend_sa_email
  instance = google_sql_database_instance.main.name
  type     = "CLOUD_IAM_SERVICE_ACCOUNT"
}

# ── Secrets ──────────────────────────────────────────────────
# DB password: generated by Terraform via random_password, so it's already in
# state regardless. Writing it to Secret Manager here is fine — it doesn't
# increase the blast radius beyond what random_password already creates.
#
# Onfido API key: externally sourced. Terraform creates the secret container
# and IAM bindings only. The VALUE is populated out-of-band via CI or gcloud:
#   gcloud secrets versions add docuvault-onfido-api-key --data-file=-
# This keeps the plaintext key out of Terraform variables, module wiring,
# and state entirely.

resource "random_password" "db_password" {
  length  = 32
  special = true
}

resource "google_secret_manager_secret" "db_password" {
  secret_id = "${var.project_name}-db-password"

  replication {
    auto {}
  }

  labels = {
    data-classification = "credential"
  }
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db_password.result
}

resource "google_secret_manager_secret" "onfido_api_key" {
  secret_id = "${var.project_name}-onfido-api-key"

  replication {
    auto {}
  }

  labels = {
    data-classification = "api-key"
  }
}

# ── Storage ──────────────────────────────────────────────────

resource "google_storage_bucket" "documents" {
  name          = "${var.project_id}-customer-documents"
  location      = "US"
  force_destroy = false

  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }

  lifecycle_rule {
    condition {
      num_newer_versions = 3
      with_state         = "ARCHIVED"
    }
    action {
      type = "Delete"
    }
  }

  lifecycle_rule {
    condition {
      days_since_noncurrent_time = 30
    }
    action {
      type = "Delete"
    }
  }

  soft_delete_policy {
    retention_duration_in_seconds = 604800
  }

  cors {
    origin          = ["https://${var.project_name}.example.com"]
    method          = ["GET", "POST", "PUT"]
    response_header = ["Content-Type"]
    max_age_seconds = 3600
  }

  labels = {
    data-classification = "customer-pii"
  }
}

# ── Resource-scoped IAM ──────────────────────────────────────

resource "google_secret_manager_secret_iam_member" "api_db_password" {
  secret_id = google_secret_manager_secret.db_password.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${var.api_backend_sa_email}"
}

resource "google_secret_manager_secret_iam_member" "api_onfido_key" {
  secret_id = google_secret_manager_secret.onfido_api_key.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${var.api_backend_sa_email}"
}

resource "google_storage_bucket_iam_member" "api_documents" {
  bucket = google_storage_bucket.documents.name
  role   = "roles/storage.objectUser"
  member = "serviceAccount:${var.api_backend_sa_email}"
}

